name: Check Lint and Type Errors

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "warning"
        type: choice
        options:
          - info
          - warning
          - debug
      tags:
        description: "Test scenario tags"
        required: false
        type: boolean
      # environment:
      #   description: "Environment to run tests against"
      #   type: environment

  pull_request:
    branches:
      - main
      - production

jobs:
  check-lint-and-type-errors:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run lint checks
        run: npx eslint.

      - name: Run type checks
        run: npx tsc --noEmit

      - name: Report results
        uses: actions/upload-artifact@v2
        with:
          name: lint-and-type-errors
          path: lint-and-type-errors.txt

      - name: Display inputs
        run: |
          echo "Log level: $LEVEL"
          echo "Tags: $TAGS"

        env:
          LEVEL: ${{ inputs.logLevel }}
          TAGS: ${{ inputs.tags }}

